### ISSUE TITLE
pip安装后无法运行

### ISSUE THREAD

**Issue by wi24rd** [messense/caiyun#1]
~ $ caiyun --help
Traceback (most recent call last):
  File "/usr/local/bin/caiyun", line 7, in <module>
    from caiyun.cli import main
  File "/usr/local/lib/python3.5/dist-packages/caiyun/cli.py", line 10, in <module>
    import baidupcsapi
  File "/usr/local/lib/python3.5/dist-packages/baidupcsapi/__init__.py", line 9, in <module>
    from .api import PCS
  File "/usr/local/lib/python3.5/dist-packages/baidupcsapi/api.py", line 1068
    print '请求url', url
                ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by messense** [comment]
baidupcsapi 只支持 Python 2
