### ISSUE TITLE
print '请求url', url

### ISSUE THREAD

**Issue by mitechen** [messense/caiyun#2]
```
`Traceback (most recent call last):
  File "/Users/mite1980/anaconda/envs/python3/bin/caiyun", line 7, in <module>
    from caiyun.cli import main
  File "/Users/mite1980/anaconda/envs/python3/lib/python3.5/site-packages/caiyun/cli.py", line 10, in <module>
    import baidupcsapi
  File "/Users/mite1980/anaconda/envs/python3/lib/python3.5/site-packages/baidupcsapi/__init__.py", line 9, in <module>
    from .api import PCS
  File "/Users/mite1980/anaconda/envs/python3/lib/python3.5/site-packages/baidupcsapi/api.py", line 1068
    print '请求url', url
                ^
SyntaxError: Missing parentheses in call to 'print'`
```

环境: Mac
Python 3.5.2 :: Anaconda 4.1.1 (x86_64)

**Comment by messense** [comment]
#1 Python 2 only.
